INSERT INTO matches (
    id,
    pair,
    ask_exchange,
    ask_price,
    ask_size,
    ask_time,
    ask_fee_rate,
    bid_exchange,
    bid_price,
    bid_size,
    bid_time,
    bid_fee_rate,
    timestamp,
    calc_volume,
    calc_price_diff,
    calc_price_avg,
    calc_spread,
    calc_spread_pct,
    calc_bid_fee,
    calc_ask_fee,
    calc_profit_loss
)
SELECT
    id,
    pair,
    ask_exchange,
    ask_price,
    ask_size,
    ask_time,
    ask_fee AS ask_fee_rate,
    bid_exchange,
    bid_price,
    bid_size,
    bid_time,
    bid_fee AS bid_fee_rate,
    timestamp,
    volume AS calc_volume,
    (bid_price - ask_price) AS calc_price_diff,
    ((ask_price + bid_price) / 2) AS calc_price_avg,
    ((bid_price - ask_price) * volume) AS calc_spread,
    ((bid_price - ask_price) / ((ask_price + bid_price) / 2) * 100) AS calc_spread_pct,
    (bid_fee / 100 * bid_price * volume) AS calc_bid_fee,
    (ask_fee / 100 * ask_price * volume) AS calc_ask_fee,
    ((bid_price - ask_price) * volume) - (bid_fee / 100 * bid_price * volume) - (ask_fee / 100 * ask_price * volume) AS calc_profit_loss
FROM alpha;